### ISSUE TITLE
ml.hmm bad messages in helpfile

### ISSUE THREAD

**Issue by batchku** [irllabs/ml-lib#103]
i quote:

error: ml.hmm: messages with the selector 'enable_trim_training_data' are not supported
error: ml.hmm: messages with the selector 'enable_z_normalization' are not supported
error: ml.hmm: messages with the selector 'constrain_warping_path' are not supported
error: ml.hmm: messages with the selector 'offset_time_series' are not supported

**Comment by jamiebullock** [comment]
The ml.hmm.maxhelp looks mostly wrong in fact. Those messages aren't supported by the object and should be removed from the helpfile.
