### ISSUE TITLE
Pd help patches

### ISSUE THREAD

**Issue by balandinodidonato** [irllabs/ml-lib#111]
Pd help patches would be very appreciated.

**Comment by batchku** [comment]
hello, 
pd-help patches are on our to-do-list for the official release, which should be by around June.
if you know of anyone who is up for helping us make pd help patches, please let us know!

-ali

**Comment by balandinodidonato** [comment]
Hi Ali! 

I may help.

I started to use the ml-lib often because of my research. I'm working with other objects taking informations from the respective Max help patch; therefore, I already started to develop a sort of Pd help patches. 
However, I noticed that they may work differently, thus I may need some more information about the objects. Is there any documentation about the them?

Balandino

**Comment by jamiebullock** [comment]
Hi Balandino, this is great. I have almost finished the documentation system and plan to release a full doc set by Friday.

For the Pd help patches it might be worth agreeing a "template" with Ali so we have a polished and consistent layout.

**Comment by balandinodidonato** [comment]
I definitely agree with you @jamiebullock. 

I look forward to reading it.
