### ISSUE TITLE
ml.dtw pd object train function returns errors.

### ISSUE THREAD

**Issue by balandinodidonato** [irllabs/ml-lib#112]
To reproduce:
- run ml.dtw in pd
- clear
- recording on
- add two gestures
- train
- recording off

Expected:
- the model is trained

Actual:
- Pd give back errors after pressing train

here follows the Pd log:

ml.dtw: recording: on
print: add 1 8 1 47 2 0 3 5 86 52 71 59 62
print: add 1 8 1 47 2 0 3 5 86 52 71 59 62
print: add 1 8 1 47 2 0 3 5 86 52 71 59 62
print: add 1 8 1 47 2 1 4 4 85 52 70 59 62
print: add 1 8 1 46 3 1 5 4 83 53 70 59 62
print: add 1 8 1 46 3 1 5 4 83 53 70 59 62
print: add 1 8 1 46 3 1 5 4 83 53 70 59 62
print: add 1 8 1 45 3 1 6 3 81 53 69 60 62
print: add 1 8 1 45 3 1 6 3 81 53 69 60 62
print: add 1 8 1 47 2 2 7 2 79 54 68 60 62
print: add 1 8 1 46 2 2 8 1 76 55 67 60 62
print: add 1 8 1 46 2 2 8 1 76 55 67 60 62
print: add 1 8 1 46 2 2 8 1 76 55 67 60 62
print: add 1 8 1 46 2 2 8 1 76 55 67 60 62
print: add 1 9 1 44 4 3 10 0 69 56 65 61 61
print: add 1 9 1 44 4 3 10 0 69 56 65 61 61
print: add 1 9 0 43 4 3 10 0 65 57 64 62 61
print: add 1 9 0 43 4 3 10 0 65 57 64 62 61
print: add 1 8 1 43 4 3 11 0 61 57 62 62 60
print: add 1 8 1 43 4 3 11 0 61 57 62 62 60
print: add 1 8 1 43 4 3 11 0 61 57 62 62 60
print: add 1 8 1 43 4 3 11 0 61 57 62 62 60
print: add 1 8 1 43 4 3 11 0 61 57 62 62 60
print: add 1 8 1 43 4 3 11 0 61 57 62 62 60
print: add 1 7 3 43 2 3 12 1 48 59 58 64 60
print: add 1 7 3 43 2 3 12 1 48 59 58 64 60
print: add 1 7 3 43 2 3 13 3 43 60 57 64 59
print: add 1 7 3 43 2 3 13 3 43 60 57 64 59
print: add 1 8 4 43 2 4 13 4 38 60 55 64 59
print: add 1 8 4 43 2 4 13 4 38 60 55 64 59
print: add 1 8 4 42 2 4 13 7 34 61 53 65 59
print: add 1 8 4 42 2 4 13 7 34 61 53 65 59
print: add 1 8 4 42 2 4 13 7 34 61 53 65 59
print: add 1 8 4 42 2 4 13 7 34 61 53 65 59
print: add 1 8 8 42 1 4 14 12 25 61 50 65 59
print: add 1 8 8 42 1 4 14 12 25 61 50 65 59
print: add 1 9 6 42 1 4 15 16 21 62 48 65 58
print: add 1 9 6 42 1 4 15 16 21 62 48 65 58
print: add 1 8 7 41 1 4 15 19 17 62 47 65 58
print: add 1 8 7 41 1 4 15 19 17 62 47 65 58
print: add 1 8 7 42 1 3 15 24 13 62 45 65 58
print: add 1 8 7 42 1 3 15 24 13 62 45 65 58
print: add 1 8 7 43 1 3 15 28 10 62 43 65 58
print: add 1 8 7 43 1 3 15 28 10 62 43 65 58
print: add 1 9 7 42 0 3 15 33 7 62 41 65 58
print: add 1 9 7 42 0 3 15 33 7 62 41 65 58
print: add 1 10 7 40 1 3 15 38 5 61 39 65 58
print: add 1 10 7 40 1 3 15 38 5 61 39 65 58
print: add 1 10 10 40 0 3 15 43 3 61 38 65 58
print: add 1 10 10 40 0 3 15 43 3 61 38 65 58
print: add 1 10 12 42 0 3 14 48 1 61 36 65 58
print: add 1 10 12 42 0 3 14 48 1 61 36 65 58
print: add 1 10 12 42 0 2 14 53 0 61 34 64 58
print: add 1 10 12 42 0 2 14 53 0 61 34 64 58
print: add 1 9 11 41 0 2 14 58 0 60 33 64 58
print: add 1 9 11 41 0 2 14 58 0 60 33 64 58
print: add 1 9 11 39 0 1 13 63 0 60 31 64 59
print: add 1 9 11 39 0 1 13 63 0 60 31 64 59
print: add 1 9 14 42 0 1 12 67 0 59 30 64 59
print: add 1 9 14 42 0 1 12 67 0 59 30 64 59
print: add 1 14 12 43 0 1 11 71 0 59 29 63 59
print: add 1 14 12 43 0 1 11 71 0 59 29 63 59
print: add 1 14 14 44 0 1 10 75 1 59 27 63 59
print: add 1 14 14 44 0 1 10 75 1 59 27 63 59
print: add 1 14 14 43 0 1 9 78 2 58 26 63 59
print: add 1 14 14 43 0 1 9 78 2 58 26 63 59
print: add 1 11 15 45 0 1 8 81 2 58 25 63 60
print: add 1 11 15 45 0 1 8 81 2 58 25 63 60
print: add 1 12 15 47 0 0 6 83 3 58 25 63 60
print: add 1 12 15 47 0 0 6 83 3 58 25 63 60
print: add 1 13 14 49 0 0 5 85 4 58 24 62 60
print: add 1 13 14 49 0 0 5 85 4 58 24 62 60
print: add 1 13 14 49 0 0 5 85 4 58 24 62 60
print: add 1 13 14 49 0 0 5 85 4 58 24 62 60
print: add 1 13 14 49 0 0 5 85 4 58 24 62 60
print: add 2 5 10 55 3 1 0 83 3 58 25 63 59
print: add 2 5 10 55 3 1 0 83 3 58 25 63 59
print: add 2 6 11 56 3 2 0 83 3 59 25 63 59
print: add 2 6 11 56 3 2 0 83 3 59 25 63 59
print: add 2 6 11 56 3 2 0 83 3 59 25 63 59
print: add 2 7 12 55 4 3 0 83 3 60 25 64 58
print: add 2 8 13 53 4 4 0 83 3 62 25 65 58
print: add 2 8 13 53 4 4 0 83 3 62 25 65 58
print: add 2 7 14 51 5 6 0 83 3 64 25 66 57
print: add 2 7 14 51 5 6 0 83 3 64 25 66 57
print: add 2 6 15 48 5 6 0 82 3 66 25 68 56
print: add 2 6 15 48 5 6 0 82 3 66 25 68 56
print: add 2 6 16 46 5 7 0 82 3 69 25 70 56
print: add 2 6 16 46 5 7 0 82 3 69 25 70 56
print: add 2 6 16 45 5 8 0 81 3 72 25 72 55
print: add 2 6 16 45 5 8 0 81 3 72 25 72 55
print: add 2 6 16 45 5 8 0 81 3 72 25 72 55
print: add 2 4 17 43 5 8 0 80 3 76 26 74 55
print: add 2 1 16 42 4 8 0 79 4 79 26 77 54
print: add 2 1 16 42 4 8 0 79 4 79 26 77 54
print: add 2 5 5 38 9 0 1 1 51 66 59 68 55
print: add 2 5 5 38 9 0 1 1 51 66 59 68 55
print: add 2 7 8 40 8 0 4 1 51 62 59 65 54
print: add 2 7 8 40 8 0 4 1 51 62 59 65 54
print: add 2 7 12 41 7 0 5 1 51 58 59 63 53
print: add 2 7 12 41 7 0 5 1 51 58 59 63 53
print: add 2 11 13 43 5 0 7 1 50 55 59 60 53
print: add 2 11 13 43 5 0 7 1 50 55 59 60 53
print: add 2 14 14 46 4 0 8 2 49 51 58 58 52
print: add 2 14 14 46 4 0 8 2 49 51 58 58 52
print: add 2 14 14 48 3 0 9 3 47 48 58 56 52
print: add 2 14 14 48 3 0 9 3 47 48 58 56 52
print: add 2 15 14 49 3 0 11 5 45 45 57 54 52
print: add 2 15 14 49 3 0 11 5 45 45 57 54 52
print: add 2 17 15 49 3 0 11 7 42 42 56 52 52
print: add 2 17 15 49 3 0 11 7 42 42 56 52 52
print: add 2 20 16 49 3 0 12 9 39 39 55 50 52
print: add 2 20 16 49 3 0 12 9 39 39 55 50 52
print: add 2 21 17 49 2 0 13 12 36 37 53 48 52
print: add 2 21 17 49 2 0 13 12 36 37 53 48 52
print: add 2 23 17 50 2 0 13 15 33 35 52 47 53
print: add 2 23 17 50 2 0 13 15 33 35 52 47 53
print: add 2 23 16 49 1 1 14 18 29 34 50 46 53
print: add 2 23 16 49 1 1 14 18 29 34 50 46 53
print: add 2 22 16 48 1 2 14 21 26 33 48 45 54
print: add 2 22 16 48 1 2 14 21 26 33 48 45 54
print: add 2 23 15 48 1 3 14 25 22 32 46 44 55
print: add 2 23 15 48 1 3 14 25 22 32 46 44 55
print: add 2 23 15 48 1 4 14 29 19 32 45 44 56
print: add 2 23 15 48 1 4 14 29 19 32 45 44 56
print: add 2 24 14 48 1 4 14 34 16 31 43 44 57
print: add 2 24 14 48 1 4 14 34 16 31 43 44 57
print: add 2 26 12 50 1 5 13 38 14 32 41 44 57
print: add 2 26 12 50 1 5 13 38 14 32 41 44 57
print: add 2 26 12 49 2 6 13 43 11 33 39 45 58
print: add 2 26 12 49 2 6 13 43 11 33 39 45 58
print: add 2 28 12 49 2 6 12 47 9 34 37 46 59
print: add 2 28 12 49 2 6 12 47 9 34 37 46 59
print: add 2 28 13 49 2 7 12 51 7 35 35 47 59
print: add 2 28 13 49 2 7 12 51 7 35 35 47 59
print: add 2 28 13 49 2 7 11 56 6 37 34 48 59
print: add 2 28 13 49 2 7 11 56 6 37 34 48 59
print: add 2 27 11 49 3 8 10 60 4 39 32 49 60
print: add 2 27 11 49 3 8 10 60 4 39 32 49 60
print: add 2 27 11 49 3 8 10 60 4 39 32 49 60
print: add 2 27 11 49 3 8 10 60 4 39 32 49 60
print: add 2 27 11 49 3 8 10 60 4 39 32 49 60
print: add 2 25 13 45 3 9 7 66 3 44 30 53 60
print: add 2 21 10 45 3 9 5 69 2 46 29 55 59
print: add 2 21 10 45 3 9 5 69 2 46 29 55 59
print: add 2 21 10 43 3 10 4 71 1 49 29 57 59
print: add 2 21 10 43 3 10 4 71 1 49 29 57 59
print: add 2 18 10 41 3 10 2 73 1 53 28 59 59
print: add 2 18 10 41 3 10 2 73 1 53 28 59 59
print: add 2 18 10 41 3 10 2 73 1 53 28 59 59
print: add 2 18 10 41 3 10 2 73 1 53 28 59 59
print: add 2 14 12 40 3 10 0 75 1 59 27 64 58
print: add 2 14 12 40 3 10 0 75 1 59 27 64 58
print: add 2 10 11 40 3 9 0 76 1 63 27 66 58
print: add 2 10 11 40 3 9 0 76 1 63 27 66 58
print: add 2 7 11 38 3 9 0 76 1 66 27 68 57
print: add 2 7 11 38 3 9 0 76 1 66 27 68 57
print: add 2 4 12 36 3 8 0 76 1 69 27 70 57
print: add 2 4 12 36 3 8 0 76 1 69 27 70 57
print: add 2 4 12 36 3 8 0 76 1 69 27 70 57
print: add 2 4 12 36 3 8 0 76 1 69 27 70 57
print: add 2 4 12 35 2 6 0 76 2 74 27 73 57
print: add 2 4 11 35 1 4 0 75 2 75 27 74 56
print: add 2 4 11 35 1 4 0 75 2 75 27 74 56
print: add 2 4 11 35 1 4 0 75 2 75 27 74 56
print: add 2 4 11 35 1 3 0 75 2 77 27 75 56
print: add 2 4 11 35 1 3 0 75 2 77 27 75 56
**(Tcl) INVALID COMMAND NAME: invalid command name "TRAINING"
    while executing
"TRAINING NDDTW"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $cmds_from_pd"**ml.dtw: recording: off

**Comment by balandinodidonato** [comment]
Consequentially I experienced errors during the map process.

"ERROR NDDTW"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $cmds_from_pd"(Tcl) INVALID COMMAND NAME: invalid command name "ERROR:"
    while executing
"ERROR: CircularBuffer"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $cmds_from_pd"

**Comment by jamiebullock** [comment]
This seems to be an issue only with Pd 0.43.4 (2012–13). It works fine with the latest Pd 0.45.4 (2014).

@batchku what are your thoughts on our policy for supporting older versions of Pd? 0.43.4 was the last version of *Pd-extended*, and I guess a lot of people use that, but I'm not sure if it's feasible to keep supporting something that is itself not under active development.

**Comment by NiccoloGranieri** [comment]
Issue is fixed using the latest version of Pd 0.49.1 and both the macOS only deken build and the _soon-to-be-released_ cross platform deken build.
