### ISSUE TITLE
Trouble using in windows with Max

### ISSUE THREAD

**Issue by pcpeterchen** [irllabs/ml-lib#120]
Hi,

I am new to Max and trying to use ml-lib.  I was wondering if there is a way to use this with windows, it seems like most people use it with Mac OSX.

Thank you.

**Comment by jamiebullock** [comment]
Hi, sorry for the slow reply.

There currently isn't a build for Windows, and there isn't a Windows build system however it was designed to run on Windows, it is just a case of doing the work.

I am therefore leaving this issue open.

**Comment by carlthome** [comment]
Hi, I too would love to see Windows binaries added to GitHub Releases.

**Comment by ThomasKirwan** [comment]
Well, I ended up getting the mac version. Do you know of any good ml-lib
tutorials? I'm working on a svm max patch for my interactive media final
and was wondering if you might know where I could get tutorial information
on the dynamic time wrapping object?

Best,

Thomas

**Comment by carlthome** [comment]
Do you mean dynamic time warping (DTW)? There's a bit of background theory to grasp first so perhaps start with learning about [dynamic programming](https://www.topcoder.com/community/data-science/data-science-tutorials/dynamic-programming-from-novice-to-advanced/). Then getting DTW should be pretty trivial.

Anyway, Windows binaries would be nice.

**Comment by ThomasKirwan** [comment]
Thank you to pointing me towards dynamic programing. I will investigate
that.
I believe that I have a basic understanding of the concept behind the DTW
module though.
My understand so far is that it is a learning algorithm that looks for a
specific wave form on a graph through time that correlates to a specific
series of events and then classifies that series as one class of event.
Once trained the module will be looking for those specific sequences to
occur.
I already have a basic SVM patch working and am building a simple
interactive media piece based on it, but would like to integrate the
ability to recognize and classify specific wave forms through time in this
piece or future works.
Do you know of any available tutorials on DTW or any of the other ml-lib
objects? I have not been able to find any through Google searching or via
YouTube.

**Comment by ThomasKirwan** [comment]
If you don't happen to know of any tutorials I understand. Thank you for
the link to the the DP article. It looks like a useful resource and I
appreciate it.

**Comment by NiccoloGranieri** [comment]
A windows build has been implemented since [v0.17](https://github.com/irllabs/ml-lib/releases/tag/0.17.0). All the following versions of ml.lib consist of cross-platform builds that run on Mac, Windows and Linux.
