### ISSUE TITLE
ml.mlp error: model has not been trained, use 'train' to train the model

### ISSUE THREAD

**Issue by ktatar** [irllabs/ml-lib#127]
Hello, 

I am using ml.mlp on Mac 10.10.5. When I train the model, I still get this error: model has not been trained. This happens after the ml.mlp printing "train 1" on max console. I am trying to implement a regression model with linear activation and output functions. Number of outputs is 400, number of hidden neurons is 128.

Max version: 
    "version" : "Version 7.2.4 (1cf59cb) (32-bit mac)",
    "platform" : "mac",
    "arch" : "x86",
    "osversion" : "Mac OS X Version 10.10.5 x86_64",
    "samplerate" : 44100,
    "iovs" : 1024,
    "sigvs" : 512,
    "scheduler_in_audio_interrupt" : "on",
    "audio_drivername" : "Core Audio",
    "audio_driver_subname" : "",
    "license" : "term",
    "machine_id" : "266cd7bfaef49fcf1c6243421a128e6b",
    "eventinterval" : 2,
    "overdrive" : "off",
    "mixerparallel" : "off",
    "mixercrossfade" : 0,
    "mixerlatency" : 30.0,
    "mixerramptime" : 10.0,
    "videoengine" : "avf",

**Comment by NiccoloGranieri** [comment]
Hi @ktatar, first of all sorry for the immensely slow reply. Are you still trying to use ml.lib to implement a regression model? If so could you try this build: 

https://www.dropbox.com/s/gf1v8k3frbv24t5/ml-0.19.0-alpha-OSX64-2.zip?dl=0

and see if the problem persists?
