### ISSUE TITLE
ml.zerox/ml.dtree ... couldn't create PD OSX

### ISSUE THREAD

**Issue by megrimm** [irllabs/ml-lib#129]
OSX Pd
Mackbook Pro (2017)

Lib seems to build fine with:

`xcodebuild -scheme 'ml.zerox pd' build`
`xcodebuild -scheme 'ml.dtree pd' build`
or
`xcodebuild -scheme 'BUILD ALL PD' build`

but get 'ml.zerox ... couldn't create' 
but get 'ml.dtree ... couldn't create'

Maybe some dependencies I am missing? Running Pd in -verbose provides no more information.

The rest load fine although I do get a 'Bad arguments for message 'loadbang' to object 'ml.softmax' ' error message on all objects.

**Comment by jamiebullock** [comment]
@megrimm did you ever resolve this? The easiest way to get working with ml-lib is to use the pre-built binaries which can be found in the [releases tab](https://github.com/irllabs/ml-lib/releases/tag/0.18.0) on GitHub. 

If this is still an issue for you, it might be worth trying the latest sources. If the problem still persists, please let me know.

**Comment by megrimm** [comment]
@jamiebullock  just tried the release build. ml.zerox creates fine. ml.dtree crashes pd immediately.... hmmm... started pd in -verbose but yielded nothing. not much time to troubleshoot today.

**Comment by AlexChisnall** [comment]
Hi, ml.dtree also crashes pd for me. I downloaded the latest pre-built libraries from github but the dll for ml.minmax doesn't seem to be in the folder

**Comment by danieleghisi** [comment]
Hi, ml.dtree does not work on Max either, for me:
"ml.dtree: unable to load extern, object has no function named 'ext_main' or 'main' "
(also it has no help file)

I'm on MacOs 10.13.6, Max 8.

**Comment by jamiebullock** [comment]
Hi @danieleghisi, would you mind trying this new build: https://www.dropbox.com/s/0eaits46emvxhts/ml.lib-0.20.1.zip?dl=0

It is bundled as a Max package (upcoming release), which you can place in your Max packages folder, usually ~/Documents/Max 8/Packages

Alternatively, you can just drag the ml.dtree.mxo and help file to wherever you keep your ml-lib externals.

This version definitely has help and works in Max 8 here.

**Comment by danieleghisi** [comment]
That's great, thanks!
Now ml.dtree work perfectly, easy to use and effective! Thanks for the
library.

Out of curiosity: what's the relationship of ml.lib with the ml.star
package? I guess they share part of the same code?
Keeping them both generates name conflicts: can I keep this new build and
delete ml.star?

Daniele

Il giorno dom 3 mar 2019 alle ore 18:49 Jamie Bullock <
notifications@github.com> ha scritto:

**Comment by jamiebullock** [comment]
Hi @danieleghisi 

Great, that's working for you now. Once we've uploaded the package you should be able to use the Max package manager from that point on.

> Out of curiosity: what's the relationship of ml.lib with the ml.star
> package? I guess they share part of the same code?

ml-lib actually has nothing to do with ml.star, and they don't share any common code. ml-lib pre-dates ml.star, but ml.star was introduced to the Max package manager first. Unfortunately the authors of ml.star didn't consult us at all when building their library and have introduced these naming conflicts. I'm not sure what the best solution to this is currently.

**Comment by danieleghisi** [comment]
Hi Jamie, thanks a lot for your reply.

I undersand. If I were you, I'd want to talk to the ml.star guys and work
out another way of naming objects: naming conflicts are the worse...
Also (again, my two cents), since machine learning will become a standard
tool (it already is, in a sense), if it were me, I would seize the
opportunity to switch from "ml" to something more evocative and unique... I
wouldn't be surprised if other libraries popped up in the near future,
covering other ML models – using "ml" for all of them would probably become
too much :)

Thanks again for all your great work.
Daniele

Il giorno lun 4 mar 2019 alle ore 11:53 Jamie Bullock <
notifications@github.com> ha scritto:
