### ISSUE TITLE
Attributes ml.svm not working

### ISSUE THREAD

**Issue by Jelkro** [irllabs/ml-lib#130]
With Pd 0.46.7
on Ubuntu 16.04 LTS
-------------------------------------
Hi,

I'm working on a project that uses the ml.svm classifier. The classification works fine, however, some of the attributes that are displayed in the help file are not working correctly. 

These return a "not supported" message:
- load /tmp/model/
- save /tmp/model/
- normalise (was this perhaps replaced by "scaling"?)

Also, after setting parameter values of Cost and Nu, the values are shown to be unchanged when retrieving them with a getcost and getnu messages.

Since classification works fine with current settings, my main concern is that I would like to be able to save and load models. 

Thanks!

**Comment by jamiebullock** [comment]
Hi @Jelkro I know this is a super old issue, and maybe you don't even use ml.lib any more, but in any case...

The correct messages for loading and saving the model are `write` and `read`. `scaling 1` is indeed the correct message for normalisation.

As for cost and nu, oddly these only get set after the model is trained. This is a detail of `libsvm`.  Maybe they get altered internally according to the training process, but in any case I didn't want to mess around with this. 

HTH
