### ISSUE TITLE
Issues compiling in Xcode

### ISSUE THREAD

**Issue by retiutut** [irllabs/ml-lib#131]
I am having a multitude of problems and error codes trying to compile ml-lib for Max. I think the PureData externals were able to compile, but not the ones for Max (which is what I need). I keep getting the error:

 /Users/Richard/Desktop/Source Code/ml-lib-master/sources/ClassificationModules/BAG/BAG.h:52:2: Expected member name or ';' after declaration specifiers

![screen shot 2017-02-20 at 6 07 56 pm](https://cloud.githubusercontent.com/assets/25914123/23145877/a9b60cda-f797-11e6-99bb-654a82940db1.png)

I'm using latest version of Xcode with Max and PureData installed. Am I missing a library or using the wrong settings to compile?

**Comment by jamiebullock** [comment]
Hi @retiutut, sorry for the massively slow reply. Did you ever get this working? If not, if you're still interested in building ml-lib from source, perhaps you could try the latest sources and let me know if this is still an issue.

**Comment by retiutut** [comment]
I'll try to compile from the dev branch using the new Xcode later. In other news, I did download the latest release and tested the compiled Max objects with Max 8 and the library seems to work!

**Comment by jamiebullock** [comment]
Hi again. I'm closing this now unless further build issues are reported.

**Comment by retiutut** [comment]
Sorry for the slow response. I tried building from the master branch and it fails with the latest version of Xcode and OS X Mojave. Here is a screenshot:

![screen shot 2018-12-17 at 9 58 38 am](https://user-images.githubusercontent.com/25914123/50098875-6b8ab580-01e2-11e9-919a-0ed9e6948cc9.png)

**Comment by jamiebullock** [comment]
Thanks @retiutut. I'm reopening this. "Multiple commands produce ..." that's an interesting error! Not seen that one before. Will look into it.

**Comment by retiutut** [comment]
Closing this issue since the 64-bit ml-lib is now in the Max Package manager.
