### ISSUE TITLE
Not working on max 7 64bit windows 10 ?

### ISSUE THREAD

**Issue by CarloCattano** [irllabs/ml-lib#132]
Hi there. I could understand if its a 32 bit only external , if so I apologize.

When adding the files to the max path location , and triggering the helpfiles , max doesnt recognize the objects ml.*  ?

**Comment by jamiebullock** [comment]
@CarloCattano sorry for the very slow reply. Currently the Windows binaries are 32-bit only. Is this a problem for you?

**Comment by jamiebullock** [comment]
Closing as ml.lib is now 64-bit and available in Max package manager.
