### ISSUE TITLE
ml.star compatibility 

### ISSUE THREAD

**Issue by dontmarryme** [irllabs/ml-lib#147]
does this library share the same credit with the ml.star library? I just wanna know if the mxo is compatible for both libraries? For example right now I know the mlp mxo is different in two libraries. Thank you!

**Comment by jamiebullock** [comment]
Hi @dontmarryme. ml.lib has nothing to do with ml.star, except unfortunately they used the same naming convention their externals as us, which leads to the annoying naming clashes you describe. 

If you are using ml.star instead of ml.lib, I'd be very interested to know the reasons though.

Thanks.
