### ISSUE TITLE
Every object crashes Max 8 when fed a wrong size vector

### ISSUE THREAD

**Issue by NiccoloGranieri** [irllabs/ml-lib#152]
When fed a wrong size vector, every object makes Max 8 crash.

To reproduce:
1. Open the help file for ml.adaboost, or any other object
2. Add the example class (add 1 0.2 0.7 0.3 0.1) and a second class that can be the same as the first for this purpose only (add 2 0.2 0.7 0.3 0.1).
3. Train the model.
4. Add a fifth element to the input vector in order to have a discrepancy between the added vector and the one that is trying to be mapped (map 0.2 0.7 0.3 0.1 0.2)
5. Press map until Max 8 crashes.

Max 8.0.3
macOS 10.14.2
MacBook Pro 15" 2015

@jamiebullock 

___________________________________
EDIT:

The same thing happens with ml.gmm, I suspect it is a common problem of all the library. Will test further.
___________________________________
EDIT:

All the object behave in the same way, they have been tested all with the procedure mentioned above.

___________________________________
EDIT:

Add [Crash Report](https://github.com/irllabs/ml-lib/files/2745184/Max_2019-01-10-121217_Niccolos-MacBook-Pro.crash.zip)

**Comment by NiccoloGranieri** [comment]
[Verbose Crash Report - ml-lib 0.20.0](https://github.com/irllabs/ml-lib/files/2873181/Max_2019-02-17-170228_Niccolos-MacBook-Pro.crash.zip)

**Comment by jamiebullock** [comment]
@NiccoloGranieri this is an interesting one. The crash log shows that that crash isn't happening in our code. In fact the call stack for the crash doesn't pass through our code at all! Maybe it's a Max bug?

A couple of questions:

1. Which version of Max are you on?
2. How many times are you clicking map before you get the crash, roughly?

**Comment by NiccoloGranieri** [comment]
@jamiebullock 
1. Latest version of Max 8 (8.0.3)
2. Yesterday when I generated the crash report 2-3 times.

**Comment by jamiebullock** [comment]
@NiccoloGranieri sorry for the slow reply on this. Is there any possibility you could perform this test on a different machine?

**Comment by JeffersonBledsoe** [comment]
Followed the reproduce instructions on a separate machine. Same specs as the original machine except with an NVIDIA graphics card. Clicking map the first time gives the correct error in max, however clicking it a second time crashes max. Zipped crashed report attached.

[Max_2019-02-26-150817_JeffersonBledsoeMacbook.crash.zip](https://github.com/irllabs/ml-lib/files/2906097/Max_2019-02-26-150817_JeffersonBledsoeMacbook.crash.zip)

**Comment by jamiebullock** [comment]
Thanks @JeffersonBledsoe that still isn't crashing in our code, but the stack trace does give a few mode clues.
