### ISSUE TITLE
macOS: ml.dtw (Dynamic Time Warping) crashes pd after a while during "mapping" 

### ISSUE THREAD

**Issue by stc** [irllabs/ml-lib#157]

**Comment by stc** [comment]
sampling, teaching is ok. have to force quit after problem occurs. 
dtw is working smoothly w/ ofxGRT
pd-0.49-1 on macOS mojave.

**Comment by jamiebullock** [comment]
Hi @stc, which version of ml-lib are you using?

Also, when you say you have to force quit, presumably Pd hangs... i.e. you get a spinning beachball?

**Comment by stc** [comment]
ml-0.18.0-alpha-OSX64, downloaded from github releases page.
more precisely: after training, probability prediction seems to work for a while, then after 10-20 secs, it becomes less reliable, finally it stucks and sometimes the whole UI freezes, it's hard to reproduce freezing, can't figure out what event causing it (no beach ball)

**Comment by jamiebullock** [comment]
I can reproduce this and am looking into it.

**Comment by jamiebullock** [comment]
@stc when you map the time series are you delimiting each "gesture" with `record 1` `record 0` ?

I think the behaviour you described occurs when record is left "on". This leads to the DTW attempting to classifier an increasingly larger and larger input matrix as more data is added with `map`

**Comment by stc** [comment]
Indeed it seems that the order of `record` and other messages were sometimes not in the right order. Thanks for looking into it
