### ISSUE TITLE
pd release, where?

### ISSUE THREAD

**Issue by jeppius** [irllabs/ml-lib#158]
Is it available a PureData release (for Osx&Win32 platforms)? I cannot manage to compile it from source. Thanks.

**Comment by jamiebullock** [comment]
The most recent Pd release can be found [here](https://github.com/irllabs/ml-lib/releases/tag/0.17.0) however, there will soon be a Deken release for all platforms so you won't need a separate download any more.

**Comment by jeppius** [comment]
Superb, many thanks!
