### ISSUE TITLE
ml.mlp missing, ml.hmmc typo, leapmotion and osc-route dependencies, bogus nothing

### ISSUE THREAD

**Issue by lesstuck** [irllabs/ml-lib#159]
Hi Jamie & Ali,

Thanks for the fab package! 

• It seems that the ml.mlp object did not make it to the release.

• Also, there's a typo in the launcher. A message box refers to ml.hmm, not ml.hmmc. Were you trying to hide your Markov model?

• The leapmotion and beloved osc-route objects require other packages. Might be nice to include a note?

• And there is a bogus object box called, appropriately, "nothing".

Looking forward to more fun and games with your awesome work,
Les

**Comment by jamiebullock** [comment]
Hi @lesstuck 

Thanks for the valuable feedback!

Replying to your issues:

> • It seems that the ml.mlp object did not make it to the release.

We renamed ml.mlp to ml.ann to avoid naming conflicts with other libraries, but it looks like we didn't update the package info.

> • Also, there's a typo in the launcher. A message box refers to ml.hmm, not ml.hmmc. Were you trying to hide your Markov model?

Same as above.

> • The leapmotion and beloved osc-route objects require other packages. Might be nice to include a note?

@NiccoloGranieri can you add a separate issue to look into the examples and link the issue back here in a comment

> • And there is a bogus object box called, appropriately, "nothing".

Is this in the master patch or in one of the object-specific help files?

**Comment by jamiebullock** [comment]
OK... there's a new release [here](https://github.com/irllabs/ml-lib/releases/tag/1.0.1) which should fix the hmm / map naming issues

@lesstuck can you confirm?

Also, is the "nothing" still there?

**Comment by NiccoloGranieri** [comment]
[Review examples shipped with ml-lib v1.0](https://github.com/irllabs/ml-lib/issues/160)

**Comment by lesstuck** [comment]
All the naming problems in the launcher and help files have been fixed.

There are still some problems in both Example 3 "Multidimensional Mapping with MLP"
and in in Example 4 "Leap Multidimensional Mapping":
• Top-level patcher still has ml.mlp instead of ml.ann
• subpatcher paf~ inside subpatcher soundz still has the mysterious nothing abstraction

and it looks like Niccolo is on the osc-route and leapmotion dependency train.

**Comment by NiccoloGranieri** [comment]
Hi @lesstuck,
thanks for providing so much insight on the latest release of ml-lib! I will add the two additional notes about the examples to the referenced issue, as I will be dealing with the example side of things. Let me know if you spot anything else!

**Comment by jamiebullock** [comment]
Thanks. I'm closing this now as the remaining issues are covered by #160
