### ISSUE TITLE
Failed building on Linux due to multiple missing dependencies

### ISSUE THREAD

**Issue by marcodsad** [irllabs/ml-lib#163]
Hi there,

I'm on Linux Mint 19 and want to install ml-lib on my machine (for Pd, obviously).

I haven't found compiled releases for pd, so I'm assuming I have to build from source.
As far as I understand from reading the issue tracker here, all dependencies should be in the ml-lib repo. However, doing make install throws a huge number of errors. The first ones were related to flext. So I compiled that from source and added all the header files to the build folder of ml-lib. 
This worked.

however now I get another similar error, it complains it cannot find lockfree/stack.hpp
So I installed libboost1.65-dev, but I still get the same error.

Am I missing something obvious about compilation and dependencies?

I cannot find compile requirements, apologies in advance if I missed them.

thank for your help,
cheers,
Marco

**Comment by NiccoloGranieri** [comment]
HI @marcodsad! The most recent Pd release can be found [here](https://github.com/irllabs/ml-lib/releases/tag/0.17.0) however, there will soon be a Deken release for all platforms so you won't need a separate download any more.

Regarding the building errors, I'll leave @jamiebullock to look into that, even though I think you won't need to build from source anymore. However, it would be still nice to get your feedback on the build process in order for us to provide users with better documentation.

**Comment by marcodsad** [comment]
Hi @NiccoloGranieri , thanks for the prompt response!

I see, thanks for the pointer. Good to know this is coming to Deken.
I can successfully instantiate the library objects in Pd, as compiled in your binary.

re: feedback on the building process, yes, definitely happy to help!
