### ISSUE TITLE
error: Build input file cannot be found VectorFloat.cpp

### ISSUE THREAD

**Issue by megrimm** [irllabs/ml-lib#165]
hello,

just tried to build and get the following error. used the simple macOs compiling instructions for pd.

Thanks!

Showing Recent Errors Only
CompileC /Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/Objects-normal/x86_64/VectorFloat.o /Users/megrimm/Development/puredata/pd-ml-lib/vendor/grt/GRT/DataStructures/VectorFloat.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target: GRT)
    cd /Users/megrimm/Development/puredata/pd-ml-lib/build/macosx/GRT
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++11 -stdlib=libc++ -fmodules -fmodules-cache-path=/Users/megrimm/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/megrimm/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.7 -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -index-store-path /Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Index/DataStore -iquote /Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/GRT-generated-files.hmap -I/Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/GRT-own-target-headers.hmap -I/Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/GRT-all-target-headers.hmap -iquote /Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/GRT-project-headers.hmap -I/Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Products/Development/include -I/Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/DerivedSources-normal/x86_64 -I/Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/DerivedSources/x86_64 -I/Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/DerivedSources -F/Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Products/Development -MMD -MT dependencies -MF /Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/Objects-normal/x86_64/VectorFloat.d --serialize-diagnostics /Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/Objects-normal/x86_64/VectorFloat.dia -c /Users/megrimm/Development/puredata/pd-ml-lib/vendor/grt/GRT/DataStructures/VectorFloat.cpp -o /Users/megrimm/Library/Developer/Xcode/DerivedData/ml-bkwbtczkcklzxzbcwuimcrcnosev/Build/Intermediates.noindex/GRT.build/Development/GRT.build/Objects-normal/x86_64/VectorFloat.o

error: Build input file cannot be found: '/Users/megrimm/Development/puredata/pd-ml-lib/vendor/grt/GRT/DataStructures/VectorFloat.cpp'

**Comment by megrimm** [comment]
never mind... i forgot to pull the submodules. dumb...

**Comment by NiccoloGranieri** [comment]
Hi @megrimm, glad you solved the issue! Let us know if you encounter any other problems while trying to build.
