### ISSUE TITLE
Should size of training vector and Input vector be matched in DTW algorithm?

### ISSUE THREAD

**Issue by jangsuJang** [irllabs/ml-lib#168]
I wanna use DTW algorithm to match a pattern which has different size.
However, only i can see is error message that
_"error: ml.dtw: invalid input length, expected 8, got 80"_
how can i solve this problem?

**Comment by NiccoloGranieri** [comment]
Hi @jangsuJang, thanks for using ml.lib. From what I understand you are training [ml.dtw] with a feature vector of size 8, and after training the model you are feeding it a vector of size 80. To my knowledge DTW can be used to classify any type of N-dimensional temporal signals but the size of the signal must remain consistent between the training data and the mapping data.

**Comment by jangsuJang** [comment]
Thank you for answering

**Comment by NiccoloGranieri** [comment]
No problem. Let me know if you need any more help.
