### ISSUE TITLE
ml.lib crashes in Pd "double precision"

### ISSUE THREAD

**Issue by jamiebullock** [irllabs/ml-lib#170]
I’ve no idea what the motivation for a double precision Pd is, but it seems that flext-based externals generally, and ml.lib specifically are causing a crash.

See this thread for more details:

https://lists.puredata.info/pipermail/pd-dev/2020-03/022322.html

**Comment by i-n-g-o** [comment]
this should be fixed in flext by now?
https://lists.puredata.info/pipermail/pd-dev/2020-03/022326.html

**Comment by jamiebullock** [comment]
Closing this as updating Flext breaks our build, so supporting 64-bit seems non-trivial.
