### ISSUE TITLE
Unable to use a read model

### ISSUE THREAD

**Issue by smolBlakofee** [irllabs/ml-lib#179]
Hi everyone,

I am using ml.ann to train and write a model. Everything works fine, but I have trouble using a pre-written model. I can read it, but when I try to map data, I get the message "error: no observations added, use 'add' to add training data".

Am I missing something obvious? I can't find an answer in the documentation or on Github about this problem.

Here is a very simple patch to reproduce my problem: [readModel.zip](https://github.com/irllabs/ml-lib/files/6586299/readModel.zip)

Thanks in advance for your help!

**Comment by NiccoloGranieri** [comment]
Hi @smolBlakofee, thanks for reporting this.

I can confirm that I'm able to reproduce this bug on Windows but not on macOS. We are working to push some fixed by the end of the week, so if we're lucky and this is an easy fix, I'll notify you when a new build is available.
