### ISSUE TITLE
Apple silicon M1

### ISSUE THREAD

**Issue by delmenhorst** [irllabs/ml-lib#182]
Hey there!

It wouldn't be a big task to compile this objects native for Apple Silicon, would it? I tried to get into it, but unfortunately this is beyond my competence at the moment. :(

I am working with pure data and it would be lovely to have these native on apple silicon.

**Comment by jamiebullock** [comment]
Hi @delmenhorst ... Native support for Apple Silicon is on our priority list and we are aiming for end of April.

In the meantime, have you tried running Max under Rosetta? If you ctrl-click the .app bundle and select Get Info, you should see an option "Open In Rosetta". If you check this and run the application, ml.lib should work.

Please reply whether this works for you or not.

**Comment by delmenhorst** [comment]
Thank you for your response!
I am actually working with pure data. 
But I had a quick look on the max help files via rosetta, there are nice! because for pd this doesn't exist. 
The same for pure data, via rosetta it is still possible to use this external.

**Comment by jamiebullock** [comment]
> Hey, is there now a M1 version?

There will be an M1 version for Max shortly in the Max package manager.

**Comment by delmenhorst** [comment]
Is it already possible to compile it for pure data?

**Comment by jamiebullock** [comment]
There is now a macOS Pd build here: https://github.com/irllabs/ml-lib/releases/tag/1.1.5

Note that this is not signed so may need some wrangling to work with Gatekeeper
