### ISSUE TITLE
ml.ann state doesn't get restored correctly on "read"

### ISSUE THREAD

**Issue by jamiebullock** [irllabs/ml-lib#184]
To reproduce:

- Open the ml.ann help patch
- `add` some training examples
- click `train`
- Change the `write` path to `/tmp/test` and click the`write`message box
- click `clear`
- Change the `read` path to `/tmp/test` and click the `read` message box
- Click the `map` message box

Expected:

- The correct class label is output from the left outlet

Actual:

 - `-1` is output from the left outlet

**Comment by NiccoloGranieri** [comment]
Does this need to be tested before fixing it or are we sure this happens consistently?

**Comment by jamiebullock** [comment]
@NiccoloGranieri It happens consistently, but I think it's only ann not other objects
