### ISSUE TITLE
a way to get a full dump out from ml.* objects?

### ISSUE THREAD

**Issue by batchku** [irllabs/ml-lib#74]
cnmat's max/pd externals have a simple message called "tellmeeverything" to which they respond by dumping a whole bunch of info to the max window, including every attribute, size of inputs/outputs, ...

could we enable something like that for our objects, especially the complex ones like hmm and mlp?

a

**Comment by jamiebullock** [comment]
I've just taken a look at CNMAT-externals and what `tellmeeverything` dumps is basically current parameter state. This is the same thing that is given by our `getattributes` message except that our `getattributes` is implemented more consistently! i.e. `getattributes` always gives you *all* attributes and is supported for every object. `tellmeeverything` only reports the values of certain parameters and for a lot of objects in CNMAT-externals it isn't implemented at all.

OTOH, our `help` message reports a list of all *supported* messages and attributes including ranges and default values.

We could implement a `tellmeeverything` that effectively calls `help` followed by `getattributes`, but this seems to me overkill, and adding an additional message where one isn't needed. What do you think?
