### ISSUE TITLE
ml.lib helpfiles in general, and ml.hmm as example

### ISSUE THREAD

**Issue by batchku** [irllabs/ml-lib#98]
the ml.hmm help patch doesn't have the right objects/messages/sends/receives in it

i could still really use a document that lists all the massages and attributes of all the objects.
something like what the max help references are like:

https://www.dropbox.com/s/meigcypol3cs343/Screenshot%202014-10-26%2013.34.29.png?dl=0

can we get something like that together?

**Comment by jamiebullock** [comment]
Closing as the help is now fixed and we have class reference [here](http://irllabs.github.io/ml-lib/)
